import {monthKey,installments,summarize,migrateData,salaryForMonth} from './finance.js';
import {createRegister} from './register.js';
import {CloudStore} from './cloud-store.js';
const icons={home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z"/>',list:'<path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01"/>',people:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 5a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 5"/>',settings:'<path d="m9 3-1 3-3 1 1 4-2 2 2 3 3-1 2 3h3l1-3 3-1-1-4 2-2-2-3-3 1-2-3z"/><circle cx="12" cy="11" r="3"/>',plus:'<path d="M12 5v14M5 12h14"/>',left:'<path d="m14 6-6 6 6 6"/>',right:'<path d="m9 6 6 6-6 6"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18M7 15h2m3 0h2"/>',card:'<rect x="2" y="4" width="20" height="16" rx="4"/><path d="M2 10h20M6 15h4"/>',arrow:'<path d="M7 17 17 7M7 7h10v10"/>',wallet:'<path d="M20 8V5H6a3 3 0 0 0 0 6h15v9H6a3 3 0 0 1-3-3V8m18 6h-6v3h6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',bag:'<rect x="4" y="7" width="16" height="14" rx="3"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/>',check:'<path d="m5 12 4 4L19 6"/>',leaf:'<path d="M20 3C9 2 2 7 5 15s17 4 15-12ZM5 21l10-12"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>'};
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.bag}</svg>`;
const people=[{id:'duda',name:'Duda',initial:'D',color:'pink'},{id:'flavio',name:'Flávio',initial:'F',color:'blue'},{id:'cleide',name:'Cleide',initial:'C',color:'orange'},{id:'luciene',name:'Luciene',initial:'L',color:'purple'},{id:'sonia',name:'Sônia',initial:'S',color:'green'}];
const months=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v/100);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=new Date();let selected=new Date(now.getFullYear(),now.getMonth(),1),page='home',personFilter='',methodFilter='',query='',navigationReady=false;
function navState(){return {leveApp:true,page,month:monthKey(selected)};}
function pushNavState(){if(navigationReady)history.pushState(navState(),'',location.href);}
function navigate(nextPage){if(nextPage===page)return;page=nextPage;personFilter='';query='';methodFilter='';pushNavState();render();}
function chooseMonth(year,month){selected=new Date(year,month,1);pushNavState();render();}
function initializeNavigation(){const state=history.state;if(state?.leveApp){page=state.page||'home';if(/^\d{4}-\d{2}$/.test(state.month||'')){const [year,month]=state.month.split('-').map(Number);selected=new Date(year,month-1,1);}}else history.replaceState({...state,...navState()},'',location.href);navigationReady=true;}
window.addEventListener('popstate',event=>{if(!event.state?.leveApp)return;page=event.state.page||'home';if(/^\d{4}-\d{2}$/.test(event.state.month||'')){const [year,month]=event.state.month.split('-').map(Number);selected=new Date(year,month-1,1);}close();render();});
const demoMonth=monthKey(selected);
const demo=[['duda',8990,'Netflix','credit',1],['duda',220000,'Notebook','credit',10],['duda',43110,'Compras do mês','credit',1],['duda',80000,'Passagens','credit',1],['duda',30000,'Mercado & café','debit',1],['flavio',42000,'Supermercado','credit',1],['flavio',300000,'Celular','credit',6],['cleide',61000,'Compras de casa','credit',1],['luciene',43000,'Óculos','credit',1],['sonia',27000,'Farmácia','credit',1]].map(([person,amount,description,method,count],i)=>({id:'demo-'+i,person,amount,description,method,count,month:demoMonth,date:`${demoMonth}-${String(24-i).padStart(2,'0')}`}));
let data;try{data=JSON.parse(localStorage.getItem('leve-v1'));}catch{}if(!data)data={salary:400000,purchases:demo,demo:true};
migrateData(data);
let cloudMessage='';const cloudStore=new CloudStore(message=>{cloudMessage=message;if(page==='settings'&&message.startsWith('Falha'))render();else if(message.startsWith('Falha'))toast(message);});
const currentSalary=()=>salaryForMonth(data,monthKey(selected));
function save(){try{localStorage.setItem('leve-v1',JSON.stringify(data));cloudStore.scheduleSave(data);return true;}catch{toast('Não foi possível salvar. O armazenamento do navegador está indisponível.');return false;}}
const rows=()=>data.purchases.flatMap(installments).filter(t=>t.month===monthKey(selected)).sort((a,b)=>(b.date||'').localeCompare(a.date||''));
const avatar=p=>`<span class="avatar ${p.color}">${p.initial}</span>`;
const tag=p=>`<span class="tag ${p.color}"><i></i>${p.name}</span>`;
function empty(title='Tudo tranquilo por aqui',text='Nenhuma transação neste mês. Que tal registrar a primeira?'){return `<div class="empty">${icon('leaf')}<h3>${title}</h3><p>${text}</p></div>`;}
function monthHeader(){return `<div class="month-control"><button class="icon-button" data-action="prev" aria-label="Mês anterior">${icon('left')}</button><button class="month-title" data-action="calendar">${months[selected.getMonth()]}<span>${selected.getFullYear()}</span></button><button class="icon-button" data-action="next" aria-label="Próximo mês">${icon('right')}</button><span class="divider"></span><button class="icon-button" data-action="calendar" aria-label="Selecionar mês">${icon('calendar')}</button></div>`;}
function transactionItem(t){const p=people.find(p=>p.id===t.person);return `<button class="transaction" data-detail="${t.id}"><span class="transaction-icon ${t.method==='debit'?'sage':''}">${icon(t.method==='debit'?'wallet':t.count>1?'bag':'card')}</span><span class="transaction-info"><strong>${esc(t.description||'Compra sem descrição')}</strong><span>${tag(p)}<span class="meta">${t.method==='credit'?'Crédito':'Débito'}${t.count>1?` <span class="dot">·</span> Parcela ${t.part}/${t.count}`:''}</span></span></span><span class="transaction-value"><strong>${money(t.amount)}</strong><small>${t.date?`${Number(t.date.slice(-2))} ${months[Number(t.date.slice(5,7))-1].slice(0,3).toLowerCase()}`:'Sem data'}</small></span>${icon('right','row-arrow')}</button>`;}
function personItem(p,all){const total=all.filter(t=>t.person===p.id&&t.method==='credit').reduce((s,t)=>s+t.amount,0);return `<button class="person-row" data-person="${p.id}">${avatar(p)}<span>${p.name}${p.id==='duda'?'<small>Você</small>':''}</span><strong>${money(total)}</strong>${icon('right')}</button>`;}
function home(){const all=rows(),s=summarize(all,currentSalary());return `<div class="page-heading">${monthHeader()}</div><div class="dashboard"><section class="summary glass"><div class="card-top"><span class="section-label">${icon('wallet')} Seu resumo do mês</span><span class="you-pill"><i></i> Só você, Duda</span></div><div class="main-numbers"><div><span class="number-label">Crédito Duda ${icon('card')}</span><strong class="primary-number">${money(s.credit)}</strong><span class="number-note">Suas compras no cartão</span></div><div class="remaining"><span class="number-label">Restante do salário ${icon('arrow')}</span><strong class="primary-number ${s.remaining<0?'negative':''}">${s.remaining===null?'—':money(s.remaining)}</strong><span class="number-note">${s.remaining===null?'Informe seu salário na aba Registro':'Livre para os seus próximos planos'}</span></div></div><div class="summary-bottom"><span>${icon('wallet')} Débito Duda <strong>${money(s.debit)}</strong></span><span>Salário do mês <b>${currentSalary()===null?'Não informado':money(currentSalary())}</b></span></div></section><section class="credit-card glass"><div class="card-top"><span class="credit-icon">${icon('card')}</span><span class="tiny-pill">CARTÃO COMPARTILHADO</span></div><span class="number-label">Fatura total</span><strong>${money(s.total)}</strong><p>O cartão de todo mundo, em um só lugar.</p><div class="credit-footer"><div class="avatar-stack">${people.map(avatar).join('')}</div><span>5 pessoas ${icon('right')}</span></div></section><section class="people-panel panel"><div class="section-heading"><div><h2>Gastos por pessoa</h2><p>Cada um com a sua parte.</p></div><span class="mini-label">NO CRÉDITO</span></div>${people.map(p=>personItem(p,all)).join('')}<div class="info-note">${icon('leaf')} Só os seus gastos saem do seu salário.</div></section><section class="transactions-panel panel"><div class="section-heading"><div><h2>Últimas transações</h2><p>Os pequenos e grandes gastos do mês.</p></div><button class="text-button" data-page="transactions">Ver todas ${icon('right')}</button></div><div>${all.length?all.slice(0,5).map(transactionItem).join(''):empty()}</div><button class="add-inline" data-action="add">${icon('plus')} Adicionar transação</button></section></div><div class="bottom-note">${icon('leaf')} Um mês de cada vez. Uma vida mais leve.</div>`;}
function transactions(){const p=people.find(p=>p.id===personFilter);const all=rows().filter(t=>(!personFilter||t.person===personFilter)&&(!methodFilter||t.method===methodFilter)&&(!query||(t.description||'Compra sem descrição').toLowerCase().includes(query.toLowerCase())));return `<div class="page-heading">${monthHeader()}</div><section class="panel full-panel"><div class="filters"><label class="search">${icon('search')}<input id="search" placeholder="Buscar uma compra" value="${esc(query)}"></label><select id="person-filter" aria-label="Filtrar pessoa"><option value="">Todas as pessoas</option>${people.map(p=>`<option value="${p.id}" ${personFilter===p.id?'selected':''}>${p.name}</option>`).join('')}</select><select id="method-filter" aria-label="Filtrar pagamento"><option value="">Crédito e débito</option><option value="credit" ${methodFilter==='credit'?'selected':''}>Crédito</option><option value="debit" ${methodFilter==='debit'?'selected':''}>Débito</option></select></div><div class="list-total"><span>${all.length} lançamentos</span><strong>${money(all.reduce((s,t)=>s+t.amount,0))}</strong></div>${all.length?all.map(transactionItem).join(''):empty('Nenhuma transação encontrada','Experimente outro filtro ou registre uma nova compra.')}</section>`;}
function persons(){return `<div class="page-heading">${monthHeader()}</div><section class="panel people-page">${people.map(p=>personItem(p,rows())).join('')}</section>`;}
function settings(){return `<div class="page-heading">${monthHeader()}</div><section class="panel settings"><h2>Salário padrão</h2><p>Usado nos meses sem um valor específico. Na aba Registro, selecione Duda → Salário recebido para informar o valor daquele mês. Alterar o padrão não muda os meses que você já personalizou.</p><form id="salary-form"><label>Salário padrão<input name="salary" inputmode="decimal" placeholder="R$ 0,00" value="${data.defaultSalary===null?'':(data.defaultSalary/100).toFixed(2).replace('.',',')}"></label><button class="primary" type="submit">Salvar padrão</button></form><hr><h2>Salvar seus dados na nuvem</h2><p>${cloudStore.signedIn?`Conectado como ${esc(cloudStore.email)}. Seus registros são sincronizados com sua conta.`:cloudStore.configured?'Conecte sua conta para sincronizar e recuperar os dados em outros dispositivos.':'Crie um projeto Supabase gratuito e informe aqui a URL e a chave publishable. Os dados financeiros não serão enviados antes do login.'}</p>${cloudStore.signedIn?`<button class="secondary" data-action="cloud-logout">Sair da conta</button>`:`<form id="cloud-config-form" class="cloud-form"><label>URL do projeto Supabase<input name="supabase-url" type="url" placeholder="https://seu-projeto.supabase.co" value="${esc(cloudStore.config.url||'')}" required></label><label>Chave publishable<input name="supabase-key" autocomplete="off" placeholder="sb_publishable_…" value="${esc(cloudStore.config.key||'')}" required></label><button class="secondary" type="submit">Salvar conexão</button></form>${cloudStore.configured?`<form id="cloud-auth-form" class="cloud-form"><label>E-mail<input name="email" type="email" autocomplete="email" required></label><label>Senha<input name="password" type="password" minlength="8" autocomplete="current-password" required></label><button class="primary" type="submit">Entrar</button><button class="secondary" type="button" data-action="cloud-signup">Criar conta</button></form>`:''}`}<p id="cloud-status" role="status">${esc(cloudMessage)}</p><h3>Seus dados neste aparelho</h3><p>Exporte também uma cópia de segurança em JSON.</p><button class="secondary" data-action="export">Exportar dados</button>${data.demo?'<div class="demo-note"><strong>Você está explorando dados de demonstração</strong><p>Comece com o seu próprio salário e suas compras quando quiser.</p><button class="text-button" data-action="clear-demo">Apagar demonstração e começar</button></div>':''}</section>`;}
function render(){document.querySelector('#app').innerHTML=`<main>${page==='home'?home():page==='register'?register.render():page==='transactions'?transactions():page==='people'?persons():settings()}</main><nav class="bottom-nav app-navigation" aria-label="Navegação principal">${[['home','Início','home'],['register','Registro','plus'],['transactions','Transações','list'],['people','Pessoas','people'],['settings','Ajustes','settings']].map(([id,label,glyph])=>`<button data-page="${id}" class="${page===id?'active':''}" ${page===id?'aria-current="page"':''}>${icon(glyph)}${label}</button>`).join('')}</nav>`;}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3500);}
let lastFocus;
function modal(content,modifier=''){lastFocus=document.activeElement;document.querySelector('#overlay').innerHTML=`<div class="modal-backdrop ${modifier?modifier+'-backdrop':''}"><section class="modal ${modifier}" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button class="close icon-button" data-action="close" aria-label="Fechar">${icon('close')}</button>${content}</section></div>`;document.body.classList.add('modal-open');setTimeout(()=>document.querySelector('.modal input, .modal button')?.focus(),0);}
function close(){document.querySelector('#overlay').innerHTML='';document.body.classList.remove('modal-open');lastFocus?.focus();}
let calendarYear;
function calendar(){modal(`<div class="eyebrow">VIAJE PELOS SEUS MESES</div><h2 id="modal-title">Escolha um mês</h2><div class="year-picker"><button class="icon-button" data-action="year-prev" aria-label="Ano anterior">${icon('left')}</button><strong>${calendarYear}</strong><button class="icon-button" data-action="year-next" aria-label="Próximo ano">${icon('right')}</button></div><div class="month-grid">${months.map((m,i)=>`<button data-month="${i}" class="${selected.getFullYear()===calendarYear&&selected.getMonth()===i?'selected':''}">${m}</button>`).join('')}</div>` ,'calendar-mobile-screen');}
function add(){modal(`<div class="eyebrow">UM REGISTRO, MAIS CLAREZA</div><h2 id="modal-title">Nova transação</h2><p class="modal-intro">Só o valor e a pessoa. O resto é com você.</p><form id="transaction-form"><label class="amount-label">Valor total <span>*</span><div class="amount-input"><span>R$</span><input name="amount" inputmode="decimal" placeholder="0,00" required autofocus autocomplete="off"></div></label><fieldset><legend>De quem é a compra? <span>*</span></legend><div class="person-options">${people.map(p=>`<label><input type="radio" name="person" value="${p.id}" required>${avatar(p)}<span>${p.name}</span></label>`).join('')}</div></fieldset><fieldset><legend>Pagamento <small>Crédito por padrão</small></legend><div class="payment-options"><label><input type="radio" name="method" value="credit" checked>${icon('card')} Crédito</label><label><input type="radio" name="method" value="debit">${icon('wallet')} Débito</label></div></fieldset><details><summary>Mais detalhes <span>Descrição, data e parcelas</span></summary><label>Descrição <small>opcional</small><input name="description" placeholder="Ex.: supermercado" maxlength="120"></label><div class="form-columns"><label>Data <small>opcional</small><input name="date" type="date"></label><label id="installment-field">Parcelas <small>opcional</small><select name="count"><option value="1">À vista</option>${Array.from({length:35},(_,i)=>`<option value="${i+2}">${i+2} parcelas</option>`).join('')}</select></label></div><p id="installment-preview" class="help"></p></details><p class="help">Sem data, usamos hoje. A primeira parcela entra no mês da compra.</p><button type="submit" class="primary submit">${icon('check')} Salvar transação</button></form>`);}
const parseMoney=value=>{const clean=value.trim().replace(/R\$\s?/g,'').replace(/\s/g,'');if(!/^\d+(?:\.\d{3})*(?:,\d{1,2})?$/.test(clean)&&!/^\d+(?:\.\d{1,2})?$/.test(clean))return NaN;return Math.round(Number(clean.includes(',')?clean.replace(/\./g,'').replace(',','.'):clean)*100);};
function detail(id){const t=rows().find(t=>t.id===id);if(!t)return;const p=people.find(p=>p.id===t.person),schedule=installments(data.purchases.find(x=>x.id===id));modal(`<div class="eyebrow">DETALHES DA COMPRA</div><h2 id="modal-title">${esc(t.description||'Compra sem descrição')}</h2>${tag(p)}<div class="detail-amount">${money(t.originalAmount)}</div><p class="help">${t.method==='credit'?'Crédito':'Débito'} · ${t.date?t.date.split('-').reverse().join('/'):'Sem data'} · ${t.count>1?t.count+' parcelas':'À vista'}</p>${t.count>1?`<h3>Parcelas desta compra</h3><div class="schedule">${schedule.map(r=>`<div class="${r.month===monthKey(selected)?'current':''}"><span>${months[Number(r.month.slice(5))-1]} ${r.month.slice(0,4)} <small>${r.part}/${r.count}</small></span><strong>${money(r.amount)}</strong></div>`).join('')}</div>`:''}<button class="danger" data-delete="${id}">Excluir ${t.count>1?'compra e todas as parcelas':'transação'}</button>`);}
const register=createRegister({getData:()=>data,getMonth:()=>monthKey(selected),monthHeader,people,money,esc,icon,parseMoney,save,render,toast,rows});
document.addEventListener('click',e=>{const target=e.target.closest('button,a');if(e.target.classList.contains('modal-backdrop'))close();if(!target)return;if(target.dataset.page){e.preventDefault();navigate(target.dataset.page);}if(target.dataset.person){personFilter=target.dataset.person;methodFilter='credit';page='transactions';pushNavState();render();}if(target.dataset.detail)detail(target.dataset.detail);if(target.dataset.month!==undefined){close();chooseMonth(calendarYear,Number(target.dataset.month));}if(target.dataset.delete){const id=target.dataset.delete;modal(`<h2 id="modal-title">Excluir esta compra?</h2><p>Todos os lançamentos e parcelas desta compra serão removidos.</p><button class="danger" data-confirm-delete="${id}">Sim, excluir compra</button><button class="secondary" data-action="close">Cancelar</button>`);}if(target.dataset.confirmDelete){data.purchases=data.purchases.filter(t=>t.id!==target.dataset.confirmDelete);save();close();render();toast('Compra excluída.');}switch(target.dataset.action){case 'prev':case 'next':chooseMonth(selected.getFullYear(),selected.getMonth()+(target.dataset.action==='prev'?-1:1));break;case 'calendar':calendarYear=selected.getFullYear();calendar();break;case 'year-prev':calendarYear--;calendar();break;case 'year-next':calendarYear++;calendar();break;case 'add':navigate('register');break;case 'close':close();break;case 'cloud-signup':{const form=document.querySelector('#cloud-auth-form');if(form){form.dataset.createAccount='true';form.requestSubmit();}break;}case 'cloud-logout':cloudStore.signOut().then(()=>{data={defaultSalary:null,monthlySalaries:{},purchases:[],demo:false};localStorage.removeItem('leve-v1');cloudMessage='Sessão encerrada.';render();});break;case 'clear-demo':modal('<h2 id="modal-title">Começar do zero?</h2><p>Isso remove os lançamentos atuais e o salário de demonstração.</p><button class="primary" data-action="confirm-clear">Limpar e começar</button><button class="secondary" data-action="close">Cancelar</button>');break;case 'confirm-clear':data={defaultSalary:null,monthlySalaries:{},purchases:[],demo:false};register.reset();save();close();render();toast('Tudo pronto para os seus registros.');break;case 'export':{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='leve-financas.json';a.click();URL.revokeObjectURL(url);toast('Cópia exportada.');break;}}});
document.addEventListener('change',e=>{if(e.target.id==='person-filter'){personFilter=e.target.value;render();}if(e.target.id==='method-filter'){methodFilter=e.target.value;render();}if(e.target.name==='method'){document.querySelector('#installment-field').hidden=e.target.value==='debit';if(e.target.value==='debit')document.querySelector('[name="count"]').value='1';}updatePreview();});
function updatePreview(){const form=document.querySelector('#transaction-form');if(!form)return;const amount=parseMoney(form.amount.value),count=Number(form.count.value);document.querySelector('#installment-preview').textContent=count>1&&amount>0?`${count}x de aproximadamente ${money(Math.floor(amount/count))}. Centavos ajustados nas primeiras parcelas.`:'';}
document.addEventListener('input',e=>{if(e.target.id==='search'){const pos=e.target.selectionStart;query=e.target.value;render();const input=document.querySelector('#search');input.focus();input.setSelectionRange(pos,pos);}if(e.target.name==='amount')updatePreview();});
document.addEventListener('submit',async e=>{e.preventDefault();if(e.target.id==='cloud-config-form'){try{cloudStore.setConfig(e.target.elements['supabase-url'].value,e.target.elements['supabase-key'].value);cloudMessage='Conexão configurada neste aparelho.';render();}catch(error){toast(error.message);}return;}if(e.target.id==='cloud-auth-form'){const create=e.submitter?.dataset.action==='cloud-signup'||e.target.dataset.createAccount==='true';e.target.removeAttribute('data-create-account');try{const result=await cloudStore.authenticate(e.target.elements.email.value,e.target.elements.password.value,create);if(result.needsEmailVerification){toast('Conta criada. Confirme o e-mail e depois entre.');return;}data=migrateData(await cloudStore.loadOrMigrate(data));localStorage.setItem('leve-v1',JSON.stringify(data));cloudMessage='Conta conectada e dados sincronizados.';render();toast('Dados seguros na nuvem.');}catch(error){toast(error.message);}return;}if(e.target.id==='salary-form'){const value=parseMoney(e.target.salary.value);if(!Number.isSafeInteger(value)||value<0){toast('Informe um salário válido.');return;}data.defaultSalary=value;if(save())toast('Salário padrão atualizado.');render();}if(e.target.id==='transaction-form'){const f=new FormData(e.target),amount=parseMoney(f.get('amount'));if(!Number.isSafeInteger(amount)||amount<=0||amount>100000000000){toast('Informe um valor maior que zero e válido.');return;}const date=f.get('date')||`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`,count=f.get('method')==='credit'?Number(f.get('count')):1;if(amount<count){toast('Cada parcela precisa ter pelo menos R$ 0,01.');return;}data.purchases.push({id:crypto.randomUUID(),amount,person:f.get('person'),method:f.get('method'),description:f.get('description').trim(),date,month:date.slice(0,7),count});if(save()){selected=new Date(Number(date.slice(0,4)),Number(date.slice(5,7))-1,1);close();render();toast('Transação salva. Mais clareza no seu mês!');}}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')close();if(e.key==='Tab'&&document.querySelector('.modal')){const focusables=[...document.querySelectorAll('.modal button,.modal input,.modal select,.modal summary')].filter(el=>el.getClientRects().length);const first=focusables[0],last=focusables.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
initializeNavigation();render();
if(cloudStore.configured)cloudStore.restore().then(async restored=>{if(!restored)return;try{data=migrateData(await cloudStore.loadOrMigrate(data));localStorage.setItem('leve-v1',JSON.stringify(data));cloudMessage='Dados atualizados da nuvem.';render();}catch(error){cloudMessage=`Falha ao carregar dados: ${error.message}`;render();}});
